language: cpp

env:
  global:
   - secure: "CRxK65M0viesmM5Qp48MWGMnDDiAvgJL8dkzmTCDIwYIwNzgHE47mppXhxAXiIUTwz1AX7ROsVTy3ZyIqxJpkXJPbz8hxxex4HcPcBUmxhBR3lSaFpCLTkcj1nU9wSkDu/rbh0q8Ju6z3T5nisfaIzHxmip9+Q2OOzygG/FdliGzLlMrDBcjPDzYvBKbb4RgEgstC3tn7b9o1sMSVqLd6VnhRQLt8dAL4ttYlm25rwFRMfJ8DL4MVZnz5lEiQ9r6g8ftdum+SGja/hFFEvGvqCxBER6y8BcUGH3AQ9Pcpt+qLis5l4MLi5eMrCtHiRvSDyFt2GkZBIhDhgcNnIz/xA+xgA02y2WxW576NKiCcKrAGrN4P4YO2pZf2GpcC6eyBO8iajCV0q1cbIcgqOqhqZZ/zNPDTdcvHE+JLnD31DTvcIXiTF74Pz8Z2XZIwb4sUSji1+mgG4f1XGVGR/Olbw+9zMk2BpWd+pBeXIEp469B7Ui+Rvu7+scgCh2e7CQSZeThCZyVRYA/oy+zwQQuR1H3zAcZRWvHltvrCb09W7FIG9AsECy6Wc3ly0vysUXEsnNOx1rbdKNw7hrPVTRqtvZfpBHb412FCCXLbAQKmpSQwBhWxt6/If0n04qtwyDtlQAL/9zl34wdv4hggpAK8UAEx1MVejLe/O8/XOToH14="

matrix:
  include:
  - os: osx
    compiler: clang

    script:
      - src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval "$src" || exit 1
      - xcodebuild -configuration Debug
      - xcodebuild -configuration Release
      - xcodebuild analyze -quiet -configuration Debug CLANG_ANALYZER_OUTPUT=plist-html CLANG_ANALYZER_OUTPUT_DIR="$(pwd)/clang-analyze" && [ "$(find clang-analyze -name "*.html")" = "" ]
      - xcodebuild analyze -quiet -configuration Release CLANG_ANALYZER_OUTPUT=plist-html CLANG_ANALYZER_OUTPUT_DIR="$(pwd)/clang-analyze" && [ "$(find clang-analyze -name "*.html")" = "" ]

    deploy:
      provider: releases
      skip_cleanup: true
      file: "build/*/*.zip"
      file_glob: true
      api_key:
        secure: yjK4zkV2m4oBULu70QZNYzdPWNPS3/YpcR6HrpnqXr6msDzB43Fyl84S6q5r0KXjxbogqk6NJIRYwzp4Il04/J+2SIR7+6l8rKls4PHPOeJaHIUwE4o1vtoMW2xZ1M/MA+15zElo/gkGXX/sKhoE+ny1/j4yuCxhj8w4AJ8iZ+WQ6g16YuAt4aBhrzh/SKdeftAeahRZXZgCZ7JUpyDPAjeJrEdRJULxPG5Oz3vKKszLwLs8LzqNSo+SnXzYHNHY0AgXj+qANiLBtfdbs3dtPlbJ0ZVP0ebQC+L1YiRxcB13/Dinwl/sTDu5l9fgRwhxR7BKvZZoi28mjMK98OB1mDPnstSt05xmDafA13MG5JK/b31rrQP4D+ONSz/aZIwVVdKzfeOPHaZFpBpBufZyySlniKpw7qbInf6xbcL94G9DcsMbT90J83foRnpAGAXvZJ/q9zUAIYyRQ88xg4a/A9ENRHXKZEd/fCK9QtkWhCtZMs0z2SQf93lKqcT8C3m0xt4FhAQhrVQmGf0FGAL07FRdiSGZUIQ1+CozwGhsKauwPhaJ4qCLsKjDL/UPLVuHtt6DVqdxDai6fwjdQd573RNk+YshxALHNLYYQhd7bO015yapO0mw2ukE49Q09vDS7DFeAw8nMKpXveCBl5MinYkToNHEKJSAoUFOZd3wOAo=
      on:
        tags: true

  - os: osx
    osx_image: xcode6.4
    compiler: clang

    script:
      - echo "This script runs coverity..."

    addons:
      coverity_scan:
        project:
          name: "acidanthera/HibernationFixup"
          description: "HibernationFixup"
        notification_email: $NOTIFICATION_EMAIL
        build_command_prepend: "src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval \"$src\" || exit 1"
        build_command: "xcodebuild -configuration Release"
        branch_pattern: master
